name: 'PR Checker'

on:
  pull_request:
    branches: [master]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout PR Head SHA
         uses: actions/checkout@v2
         with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0
       - run: echo "✅   ${{ github.event.pull_request.head.sha }} has been checkout"
       - name: Setup pyhton and Run Test
         uses: actions/setup-python@v2
         with:
            python-version:  '2.x'
            architecture: 'x64'
       - run: 'make test'